### PR TITLE
feat(#9): Add prettier-vscode

### PR DESCRIPTION
**Pull request by edmundmiller**
Merge when https://github.com/nf-core/tools/issues/1457 is ready

### CODE REVIEW

**Comment by mashehu** [comment]
Please don't forget to add it to the gitpod.yml in the nf-co.re repo (if it available in that extension marketplace)

**Comment by edmundmiller** [comment]
Good catch! I'm adding it in the dependancies.

**Comment by mashehu** [comment]
sorry, looked it up, it is already in the nf-co.re repo gitpod.yml, but not in the tools gitpod.yml including the template.

**Review by mashehu — CHANGES_REQUESTED** [review]
we list all of them also in the readme of this repo, so please mention prettier also there

**Review by mashehu — APPROVED** [review]

**Pull request merged**
